# Docker Compose configuration
## Save as: docker-compose.yml


services:
  users-service:
    build: 
      context: .
      dockerfile: users_service/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - microservices-network
    environment:
      - FLASK_ENV=development
      - SERVICE_HOST=0.0.0.0

  orders-service:
    build:
      context: .
      dockerfile: orders_service/Dockerfile
    ports:
      - "5002:5002"
    networks:
      - microservices-network
    environment:
      - FLASK_ENV=development
      - SERVICE_HOST=0.0.0.0
    depends_on:
      - users-service

networks:
  microservices-network:
    driver: bridge